### ISSUE TITLE
failed to resolve: com.jakewharton:kotterknife:0.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by jien** [JakeWharton/kotterknife#15]
when I add compile 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT' to my gradle file,it didn't work and show failed to resolve: com.jakewharton:kotterknife:0.1.0-SNAPSHOT message.This is my build.gredle file.
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    compileSdkVersion 22
    buildToolsVersion "23.0.0 rc2"

    defaultConfig {
        applicationId "jien.kotlinandroid"
        minSdkVersion 16
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
//        main.java.srcDirs += 'src/main/kotlin'
        debug.java.srcDirs += 'src/main/kotlin'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT'
    compile 'com.android.support:recyclerview-v7:22.2.0'
}

buildscript {
    ext.kotlin_version = '0.12.200'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
repositories {
    mavenCentral()
}

**Comment by JakeWharton** [comment]
From the `README`:

> Currently not available via Maven Central.
>
> A SNAPSHOT is available in the Sonatype snapshot repo.

You have to add https://oss.sonatype.org/content/repositories/snapshots/ as a repository to your `repositories` block.

**Comment by Giszmo** [comment]
Or to be slightly more verbose, change your repositories to:

````
repositories {
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}
````

**Comment by larsblumberg** [comment]
@Giszmo Thanks for providing a copy-and-paste solution!

**Comment by DasCody** [comment]
@Giszmo or to be slightly even more verbose, if you're adding this to your Project gradle file, make sure it's under `allprojects` example:

```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
}
```

Though it seems `mavenCentral()` is not necessary.

**Comment by Giszmo** [comment]
@DasCody well, you need a repo. `jcenter()` does the trick, too.

**Comment by spragucm** [comment]
Compile is obsolete and the so the full solution is now:

File: **project/gradle.build**
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
}
```
File: **app/gradle.build**
```
dependencies {
    implementation 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT'
}
```

Then, just use:
```
public class PersonView(context: Context, attrs: AttributeSet?) : LinearLayout(context, attrs) {
  val firstName: TextView by bindView(R.id.first_name)
  val lastName: TextView by bindView(R.id.last_name)

  // Optional binding.
  val details: TextView? by bindOptionalView(R.id.details)

  // List binding.
  val nameViews: List<TextView> by bindViews(R.id.first_name, R.id.last_name)

  // List binding with optional items being omitted.
  val nameViews: List<TextView> by bindOptionalViews(R.id.first_name, R.id.middle_name, R.id.last_name)
}
```
