### ISSUE TITLE
Don't update kotlin version without updating library version number

### ISSUE THREAD

**Issue by caske33** [JakeWharton/kotterknife#22]
2 days ago with commit ffb62b043, the kotlin version was updated. This was also pushed to the sonatype repository, but the version wasn't changed. This forces all people who use the library to update their kotlin version as well.

Unfortunately, this kotlin version has a bug with proguard so we can't update yet. 

As you might see, this effectively blocks us from publishing an app. Therefore, I suggest that updating the kotlin version should also force an update in the version number, that way, people can choose to update their kotlin version or not.

**Comment by JakeWharton** [comment]
You shouldn't be depending on SNAPSHOT versions unless you accept the fact that they're prone to breakage at any time. As this entire library is a single file, it's very easily copyable into your source tree for hermetic builds. This is even mentioned in the README.

Regardless of the Kotlin breakage, there's been no API guarantees offered here (hence both the non-1.0 version and SNAPSHOT versions) so I still reserve the right to make breaking changes at any time.
