### ISSUE TITLE
Why does't upload kotterknife to Maven Central ?

### ISSUE THREAD

**Issue by pine613** [JakeWharton/kotterknife#36]
Hello, Jake.
I love Kotlin and kotterknife.

Today, I has not be able to compile my Android project because kotterknife uses Kotlin RC.

```
+--- com.jakewharton:kotterknife:0.1.0-SNAPSHOT
|    +--- com.android.support:support-v4:23.1.1 (*)
|    +--- com.android.support:recyclerview-v7:23.1.1
|    |    +--- com.android.support:support-annotations:23.1.1 -> 23.1.0
|    |    \--- com.android.support:support-v4:23.1.1 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.0.0-rc-1036 (*)
```

My project is used Kotlin beta 3 in production environment, so I was troubled very much.
Could you release kotterknife, and upload to Maven Central ?

Thank you.

**Comment by lolkittens** [comment]
You can use JitPack and add kotterknife to your project from the commit before RC.

[https://jitpack.io/#JakeWharton/kotterknife/36ae6d5ecb](https://jitpack.io/#JakeWharton/kotterknife/36ae6d5ecb)

**Comment by pine613** [comment]
Oh! Thanks!
