### ISSUE TITLE
bindView doesn't work with CheckBox

### ISSUE THREAD

**Issue by jibbo** [JakeWharton/kotterknife#39]
This is the error given by the compiler:

`Missing setValue(MyActivity.kotlin.reflect.KProperty<*>,android.widget.Checkbox) method on delegate of type kotlin.properties.ReadOnlyProperty<android.app.Activity, android.widget.Checkbox>`

**Comment by jibbo** [comment]
I was completely dumb instead of using `val` I used `var` that's why.

**Comment by mmmarklu** [comment]
lol me too
