### ISSUE TITLE
Cant bind coordinatorLayout

### ISSUE THREAD

**Issue by lectricas** [JakeWharton/kotterknife#44]
![screenshot 2016-07-14 22 57 13](https://cloud.githubusercontent.com/assets/8782219/16852802/af736486-4a1a-11e6-9780-a9e16705e63f.png)
not sure what I'm doing wrong.

**Comment by DrewCarlson** [comment]
It's saying the delegate doesn't have a `setValue` method. `cLayout` should be a `val` not `var`.

**Comment by lectricas** [comment]
oh, sorry. My bad.
