### ISSUE TITLE
hello,does it support Recyclerview?

### ISSUE THREAD

**Issue by fly7632785** [JakeWharton/kotterknife#52]
hi,look at this 
![c44fd1b0-a237-4d63-a42e-b3dc2ce3867a](https://cloud.githubusercontent.com/assets/10276266/24995113/1d786186-2060-11e7-93dc-50b11274d2e6.png)
![a85939fb-bc72-4fb9-8995-a2ebfb4787b7](https://cloud.githubusercontent.com/assets/10276266/24995124/26722e48-2060-11e7-9011-0ab68e994b66.png)

Maybe ,it doesn't support RecyclerView  or AppCompatActivity?

**Comment by DrewCarlson** [comment]
Change
`var recy1er by bindView<RecyclerView>(R.id.recycler)`
to
`val recy1er by bindView<RecyclerView>(R.id.recycler)`

The Type behind `bindView` is read only (`ReadOnlyProperty<>`) and does not have a set value method.

**Comment by JakeWharton** [comment]
Thanks, @DrewCarlson!

**Comment by fly7632785** [comment]
@DrewCarlson  That's right    , tks!
