### ISSUE TITLE
Will @OnClick be added?

### ISSUE THREAD

**Issue by taingmeng1** [JakeWharton/kotterknife#57]
Annotations from Butterknife like `@OnClick` or `@OnItemLongClick` are not added in Kotterknife. Is this in the road map? Although `view.setOnClickListener{...}` from Kotlin is pretty clean, but it would be great if we can have the same code style like Butterknife.

**Comment by JakeWharton** [comment]
No plans. Lambdas are easy enough like you said.

**Comment by sharyuke** [comment]
it's hart to switch old code to new one.
