### ISSUE TITLE
Problem with appcompat-v7:26.1.0

### ISSUE THREAD

**Issue by egek92** [JakeWharton/kotterknife#69]
```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots"}
    mavenCentral()
}
```

`compile 'com.jakewharton:kotterknife:0.1.0-SNAPSHOT'`

Manifest merger fails with 26.1.0, chaing appcompat version to 26.0.2 solves the issue however.

**Comment by JakeWharton** [comment]
It's not an issue with this library. Use Gradle's resolution strategy to force particular versions.
