### ISSUE TITLE
NPE on ReadOnlyProperty.getValue 

### ISSUE THREAD

**Issue by ncapdevi** [JakeWharton/kotterknife#75]
`                                          Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object kotlin.properties.ReadOnlyProperty.getValue(java.lang.Object, kotlin.reflect.KProperty)' on a null object reference
`

I am subclassing a FrameLayout, and have this:
`    val backgroundImage: ImageView? by bindOptionalView(R.id.row_background)
`
then I am overriding the setBackground like this

```
  override fun setBackground(background: Drawable?) {
        if (backgroundImage != null) {
            backgroundImage?.apply { setImageDrawable(background) }
        } else {
            super.setBackground(background)
        }
    }
```
the problem is that this will be called before the layout has finished inflating and butterknife has had a chance to bind it, so a NPE is called, the only solution I've found is to add a boolean that gets set to true in the `onFinishInflate()` method  and chances the above method to

```

    override fun onFinishInflate() {
        super.onFinishInflate()
        ButterKnife.bind(this)
        isInflated = true
    }

  override fun setBackground(background: Drawable?) {
        if (isInflated && backgroundImage != null) {
            backgroundImage?.apply { setImageDrawable(background) }
        } else {
            super.setBackground(background)
        }
    }
```
I am not sure if there's a better way around this

**Comment by JakeWharton** [comment]
There is no way around this with the library. The superclass constructor is calling `setBackground` which is then being routed to the subclass and accessing the property before the subclass constructor has completed (which initializes the property). Additionally, the constructor runs before any child views have been added so even if the property were initialized the call to `findViewById` would return `null`.

Waiting for `onFinishInflate` is the best you can do here.
