### ISSUE TITLE
error with suport libraries.

### ISSUE THREAD

**Issue by weijinhuang** [JakeWharton/kotterknife#77]
there is en error when I use kotterknife in my project：
"All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.0.2, 25.4.0. Examples include `com.android.support:recyclerview-v7:26.0.2` and `com.android.support:animated-vector-drawable:25.4.0`”
My project just use 25.4.0 support libraries. If I remove kotterknife, there is no problem.

**Comment by JakeWharton** [comment]
This is a problem in your build system, not the library. If you're using Gradle, consider forcing all support library artifacts to the same version like this: https://github.com/JakeWharton/u2020/blob/af670f964a4750707d98cda31cfa95244eb3ec07/build.gradle#L105-L113

**Comment by weijinhuang** [comment]
It works, thank you so much !
