### ISSUE TITLE
Abandoned repo

### ISSUE THREAD

**Issue by x1unix** [JakeWharton/kotterknife#83]
Is this repo maintained?

**Comment by x1unix** [comment]
@JakeWharton, can you mark this repo as *not maintained* (GitHub allows to do in settings)?

**Comment by JakeWharton** [comment]
No. That makes it read-only.

**Comment by neiljaywarner** [comment]
What do you use to bind your views at this point in mid 2019?
Synthetics seem to have fallen out of favor...viewbinding library not stable yet..

**Comment by JakeWharton** [comment]
View bindings!

**Comment by neiljaywarner** [comment]
With Android studio 3.6 canary?

**Comment by JakeWharton** [comment]
Sadly it's not available in the current one. Probably 2-4 weeks it'll be
there and ready to try.
